language: csharp
mono: none
dotnet: 2.0.0
dist: trusty
script:
 - (cd Memoriser.App && npm install)
 - dotnet build
 - dotnet test ./Memoriser.UnitTests\Memoriser.UnitTests.csproj --no-build --no-restore