version: '1.0.{build}'
image: Visual Studio 2017
branches:
  only:
  - master
environment:
  COVERALLS_REPO_TOKEN: DSbDszuVgmNUHt2HFmskWQs0RYlmZ1EZ4
init:
  # Good practise, because Windows line endings are different from Unix/Linux ones
  - cmd: git config --global core.autocrlf true
install:
  - cmd: cd Memoriser.App
  - cmd: npm install --silent
  - cmd: cd ..
before_build:
  - cmd: dotnet --version
build_script:
  - cmd: dotnet build
after_build:
  # For once the build has completed
clone_depth: 1
test_script:
  - cmd: mkdir coverage
  - cmd: dotnet add .\Memoriser.UnitTests\Memoriser.UnitTests.csproj package OpenCover --package-directory packages
  - cmd: dotnet add .\Memoriser.UnitTests\Memoriser.UnitTests.csproj package ReportGenerator --package-directory packages
  - cmd: dotnet add .\Memoriser.UnitTests\Memoriser.UnitTests.csproj package coveralls.net --package-directory packages
  - cmd: dotnet test Memoriser.UnitTests\Memoriser.UnitTests.csproj -c Release
  - cmd: dotnet test Memoriser.IntegrationTests\Memoriser.IntegrationTests.csproj -c Release
  - cmd: packages\opencover\4.6.519\tools\OpenCover.Console.exe -target:"dotnet.exe" -targetargs:"test -c Release Memoriser.UnitTests\Memoriser.UnitTests.csproj" -mergeoutput -output:coverage/coverage.xml -oldStyle -filter:"+[Memoriser*]* -[Memoriser.UnitTests*]* -[Memoriser.Infrastructure]Memoriser.Infrastructure.Migrations.*" -hideskipped:File -register:user -searchdirs:Memoriser.UnitTests\bin\Release\netcoreapp2.0
  - cmd: packages\opencover\4.6.519\tools\OpenCover.Console.exe -target:"dotnet.exe" -targetargs:"test -c Release  Memoriser.IntegrationTests\Memoriser.IntegrationTests.csproj" -mergeoutput -output:coverage/coverage-integration.xml -oldStyle -filter:"+[Memoriser*]* -[Memoriser.IntegrationTests*]* -[Memoriser.Infrastructure]Memoriser.Infrastructure.Migrations.*" -hideskipped:File -register:user -searchdirs:Memoriser.IntegrationTests\bin\Release\netcoreapp2.0
  - cmd: packages\reportgenerator\3.0.0\tools\ReportGenerator.exe -reports:"coverage\coverage.xml;coverage\coverage-integration.xml" -targetdir:coverage -verbosity:Error
  - cmd: packages\coveralls.net\0.412.0\tools\csmacnz.Coveralls.exe --opencover -i coverage\coverage.xml --useRelativePaths
on_finish :
  # any cleanup in here
deploy: off