// <auto-generated />
using Memoriser.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace Memoriser.Infrastructure.Migrations
{
    [DbContext(typeof(LearningItemContext))]
    [Migration("20170823121742_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Memoriser.ApplicationCore.Models.LearningItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("IntervalId");

                    b.Property<string>("ToBeGuessed");

                    b.Property<string>("_acceptedAnswers")
                        .HasColumnName("AcceptedAnswers")
                        .HasAnnotation("PropertyAccessMode", PropertyAccessMode.Field);

                    b.HasKey("Id");

                    b.HasIndex("IntervalId");

                    b.ToTable("LearningItems");
                });

            modelBuilder.Entity("Memoriser.ApplicationCore.Models.RepetitionInterval", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<float>("EasinessFactor");

                    b.Property<int>("Interval")
                        .HasAnnotation("PropertyAccessMode", PropertyAccessMode.Field);

                    b.HasKey("Id");

                    b.ToTable("RepetitionIntervals");
                });

            modelBuilder.Entity("Memoriser.ApplicationCore.Models.LearningItem", b =>
                {
                    b.HasOne("Memoriser.ApplicationCore.Models.RepetitionInterval", "Interval")
                        .WithMany()
                        .HasForeignKey("IntervalId");
                });
#pragma warning restore 612, 618
        }
    }
}
